# String Operations


- How to split a string into multiple strings
- How to change string letters to upper and lower case
- How to replace specific portions of a string
- How to format a string based on our input.

## Introduction

In the previous lesson we found the dominant artist on Spotify (Ed Sheeran) by writing a program using list comprehensions and lambda functions. For those unfamiliar with Ed Sheeran, Ed Sheeran is an english singer, songwriter and producer. [Ed Sheeran](https://en.wikipedia.org/wiki/Ed_Sheeran) has produced grammy award winning singles [Thinking Out Loud](https://www.youtube.com/watch?v=lp-EO5I60KA), [Shape of You](https://www.youtube.com/watch?v=JGwWNGJdvx8) and many more.

In this section, we'll be creating a mad libs of Ed Sheeran's song [The A Team](https://www.youtube.com/watch?v=UAWcs5H-qgQ). [Mad Libs](https://en.wikipedia.org/wiki/Mad_Libs) is a game where we take a story and remove certain words:

```
My mind was [VERB]-ing. After spending a day learning about [TOPIC], I couldn't [VERB] for another minute.

I stepped outside my [NOUN], only to see a(n) [NOUN] outside my window. As the [NOUN] struck the [NOUN],

a [NOUN] filled my [NOUN]. I ran out of the [NOUN] and [VERB]-ed. A newfound sense of [NOUN] arose.
```

After removing the words, we replace these words with our own words. Often times, the ensuing story is comical and non-sensical:

```
My mind was [swimming]-ing. After spending a day learning about [dirt], I couldn't [eat] for another minute.

I stepped outside my [house], only to see a(n) [polar bear] outside my window. As the [polar bar] struck the [horse],

a [snowman] filled my [house]. I ran out of the [house] and [screamed]-ed. A newfound sense of [peace] arose.
```

In this section, we'll taking Ed Sheeran's lyrics and transforming his lyrics into a mad libs game. We'll write a program that:

- Detects the nouns, verbs and adjectives in his lyrics.

- Replaces these nouns, verbs and adjectives with placeholders.

- Then, we'll replace these placeholders with our own words.

If you'd like to see the lyrics to this song, click [here](https://www.azlyrics.com/lyrics/edsheeran/theateam.html). Here's a sample of the first few lines of the song:

```
White lips, pale face

Breathing in snowflakes

Burnt lungs, sour taste

........
```

Through the process of creating this mad libs program, you'll learn how to:

- Plan out your program using pseudo-code

- Split a string into multiple strings

- Change string letters to upper and lower case

- Concatenate two strings into one

- Replace specific portions of a string

- Format a string based on our input.

Let's get started!

**Exercise**

<left><img width="100" src="https://drive.google.com/uc?export=view&id=1E8tR7B9YYUXsU_rddJAyq0FrM0MSelxZ"></left>


1. Insert a new line between **"face"** and **"breathing"** by adding **\n** within **lyrics**.
2. Print **lyrics** and confirm the changes.

In [18]:
lyrics = ' white lips, pale face \n breathing in snowflakes'

# put your code here
# lyrics = lyrics[:lyrics.find("face")] + "\n " + lyrics[lyrics.find("breathing"):]
lyrics

' white lips, pale face \n breathing in snowflakes'

## Planning out your code using psuedo-code

Whenever we need to write a program to perform a specific action, we undergo a subconscious, internal process:


<img width="200" src="https://drive.google.com/uc?export=view&id=1g27k9QsGvIymYH39uNZ7N2S1S4mSuOmj">

For simple programs, we can perform this steps in our heads. However, for more complex programs (like creating the mad libs program), we'll need to write **pseudo code**. Pseudo-code helps us organize our thoughts and outlines what our program is going to do before we write any code. The more concepts/ideas we put into our short-term memory, the more we need to manage.

Let's examine these three steps through the lens of finding the length of a list:


<img width="400" src="https://drive.google.com/uc?export=view&id=1X3VZ2ls9raHBQJecjxe-WQhlkcf1StrS">


Notice, for step two, we wrote out the logic for finding the length, without writing it in code. There is no one, correct way of writing pseudo-code. The purpose of pseuod-code is to assist you in writing out your logic so there's no singular correct answer. You can write your pseudocode on a notepad, in a word document, as comments etc. Experiment to see which style you prefer.

While writing pseudo-code, it's useful to make drawings of what your program does. Here's what our pseudo-code might look like with drawings:


<img width="800" src="https://drive.google.com/uc?export=view&id=10M33m0SkBT5pXFxovhU8HWszD0a9lPzd">

We'll be using this pseudocode to write our mad libs program. Make sure you understand the logic of the code!

## Splitting a string into a list

Using our pseudocode, the next step will be to split our string into multiple lists:

<img width="300" src="https://drive.google.com/uc?export=view&id=1pJ5T0oW70F2kjdKs3HOWlgDexcLvBKrw">


As review, we'll be using the **split()** method. The **split()** method takes as an input. Within the parenthesis, we specify the delimiter. The delimiter is what the method will split the string on. For example:

```python
sample = "hello, world"
split_list = sample.split(",")
```

This would split **"hello, world"** by **","**:

```python
['hello', ' world']
```

What if we didn't specify any delimiter? How would this get split?

```python
sample = "hello, world"
split_list = sample.split()
```

By default, **split()** will split the string by one space. As a result, this returns:

```python
['hello,', 'world']
```

Since each line in our lyrics is separated by a **\n**, let's split our list by **\n**!

**Exercise**

<left><img width="100" src="https://drive.google.com/uc?export=view&id=1E8tR7B9YYUXsU_rddJAyq0FrM0MSelxZ"></left>




1. Split the **lyrics** by **"\n"** and assign the result to **a_team.**

In [12]:
lyrics = ' white lips, pale face \n breathing in snowflakes \n burnt lungs sour taste \n \
lights gone days end \n struggling to pay rent \n long nights strange men \n and they say \
\n shes in the class a team \n stuck in her daydream \n been this way since 18 \n but \
lately her face seems  \n slowly sinking wasting \n crumbling like pastries \n they scream \
\n the worst things in life come free to us \n cause were just under the upperhand \n and \
go mad for a couple grams \n and she dont want to go outside tonight \n and in a pipe she \
flies to the motherland \n or sells love to another man \n its too cold outside \n for angels \
to fly \n angels to fly \n ripped gloves raincoat \n tried to swim stay afloat \n dry house wet \
clothes \n loose change bank notes \n wearyeyed dry throat \n cool girl no phone \n and they say \n \
shes in the class a team \n stuck in her daydream \n been this way since 18 \n but lately her face \
seems \n slowly sinking wasting \n crumbling like pastries \n and they scream \n the worst things in \
life come free to us \n cause were just under the upperhand \n and go mad for a couple grams \n but she \
dont want to go outside tonight \n and in a pipe she flies to the motherland \n or sells love to another \
man \n its too cold outside \n for angels to fly \n an angel will die \n covered in white \n closed eye \n \
and hoping for a better life \n this time well fade out tonight \n straight down the line \n and they say \n \
shes in the class a team \n stuck in her daydream \n been this way since 18 \n but lately her face seems \
\n slowly sinking wasting \n crumbling like pastries \n they scream \n the worst things in life come free \
to us \n and were all under the upperhand \n go mad for a couple grams \n and we dont want to go outside tonight \
\n and in a pipe we fly to the motherland \n or sell love to another man \n its too cold outside \n for angels to \
fly \n angels to fly \n to fly fly \n for angels to fly to fly to fly \n angels to die'

# put your code here

a_team = lyrics.split("\n")
a_team[:3]

[' white lips, pale face ',
 ' breathing in snowflakes ',
 ' burnt lungs sour taste ']

## Changing the values of an immutable object

Moving to the next step of our pseudo code, to change the first letter to an uppercase, we'll need to split each line into a list of characters:

<img width="300" src="https://drive.google.com/uc?export=view&id=1fbCzyAT2CqTxdNEnW28M33csjPjTBbP3">


In the previous lessons, we learned that we can access specific values in a string using a list index notation:

```python
name = 'ed sheeran'

name[0]
```

This would return:

```python
'e'
```

What if we wanted to replace this **'e'** with an **'a'**? Could we just replace the value at the specified index?

```python
name = 'ed sheeran'

name[0] = 'a'
```

Running this code will produce a **TypeError** error:

```python
TypeError: 'str' object does not support item assignment
```

We cannot assign items to a **str** object because **str** objects are immutable. 
- Immutable objects cannot be changed after they are created. 
- mutable objects can be changed after they are created.

Whenever we create a new object like name, this object is stored in memory with a memory address. Think of a memory address like a unique, personal home address for each value.:

<img width="400" src="https://drive.google.com/uc?export=view&id=1uNuqms9uRcTYre8-8i6GN7zJN1NGtkGB">


**id()** will give us the memory address.

Now, let's say we wanted to change the values of the **name** object to **'beyonce'**. Because the values ,**'ed sheeran'**, are immutable, Python will automatically make a copy of the object and store **'beyonce'** as the values:

<img width="400" src="https://drive.google.com/uc?export=view&id=1MsgEVKDkUV7Ncr7wgLM-QuKOUQRcFN2l">

Even though we're replacing the values in **name**, the new variable is stored in a different memory location. For immutable objects, we can never directly change the values at the same memory address. Instead, python makes a copy of the values in a new address.

However, if we wanted to change a **mutable** object, we can directly change the value at the same memory address:


<img width="400" src="https://drive.google.com/uc?export=view&id=1yIxc3RwM31rs5pcZW7kfjnqfTgfWpN0K">

Notice, that the memory address of **streams** is still the same. Here are the list of immutable and mutable objects:

| Immutable | Mutable |
|-----------|----------------------|
| int | list |
| float | dict |
| decimal | set |
| complex | bytearray |
| bool | user-defined classes |
| string |  |
| tuple |  |
| range |  |
| frozenset |  |
| bytes |  |


Since we want to make a change to an **immutable** object, one method would be to copy the string into a **mutable** object( a **list**) and then change it's values:

```python
name = 'ed sheeran'
name = list(name)
name[0] = 'a'
```

Printing this would return:

```python
['a', 'd', ' ', 's', 'h', 'e', 'e', 'r', 'a', 'n']
```

**list()** is a built-in method that takes in a sequence of values and converts them into a list. Let's use **list()** to convert our **lyrics** into characters!


**Exercise**

<left><img width="100" src="https://drive.google.com/uc?export=view&id=1E8tR7B9YYUXsU_rddJAyq0FrM0MSelxZ"></left>


1. Use a list comprehension to loop through **a_team** and convert each line into a list.
2. **Store** the resulting list of lists in the variable **ed_sheeran**.

In [13]:
# put your code here
ed_sheeran = [list(i) for i in a_team]
ed_sheeran[:3]

[[' ',
  'w',
  'h',
  'i',
  't',
  'e',
  ' ',
  'l',
  'i',
  'p',
  's',
  ',',
  ' ',
  'p',
  'a',
  'l',
  'e',
  ' ',
  'f',
  'a',
  'c',
  'e',
  ' '],
 [' ',
  'b',
  'r',
  'e',
  'a',
  't',
  'h',
  'i',
  'n',
  'g',
  ' ',
  'i',
  'n',
  ' ',
  's',
  'n',
  'o',
  'w',
  'f',
  'l',
  'a',
  'k',
  'e',
  's',
  ' '],
 [' ',
  'b',
  'u',
  'r',
  'n',
  't',
  ' ',
  'l',
  'u',
  'n',
  'g',
  's',
  ' ',
  's',
  'o',
  'u',
  'r',
  ' ',
  't',
  'a',
  's',
  't',
  'e',
  ' ']]

## Uppercasing And Lowercasing Strings

Now that we've converted our string into a list of characters, we can transform the first character from lowercase to uppercase.

To change a **str** into an **upper** or **lower** case string, we'll use the **upper()** and **lower()** methods. **upper()** and **ower()** are methods of the string class. To use these methods, let's look at an example by changing **'ed sheeran'** to **uppercase**:

```python
name = 'ed sheeran'
name = list(name)
name[0] = name[0].upper()
```

This would print:

```python
['E', 'd', ' ', 's', 'h', 'e', 'e', 'r', 'a', 'n']
```

Let's change each line in our lyrics to an upper case!



**Exercise**

<left><img width="100" src="https://drive.google.com/uc?export=view&id=1E8tR7B9YYUXsU_rddJAyq0FrM0MSelxZ"></left>

1. Loop through the **ed_sheeran** list.
2. Change the character the first index of each iterable into an uppercase.
3. Print **ed_sheeran**.

In [14]:
# put your code here
for i in ed_sheeran:
    i[1] = i[1].upper()
print(ed_sheeran)

[[' ', 'W', 'h', 'i', 't', 'e', ' ', 'l', 'i', 'p', 's', ',', ' ', 'p', 'a', 'l', 'e', ' ', 'f', 'a', 'c', 'e', ' '], [' ', 'B', 'r', 'e', 'a', 't', 'h', 'i', 'n', 'g', ' ', 'i', 'n', ' ', 's', 'n', 'o', 'w', 'f', 'l', 'a', 'k', 'e', 's', ' '], [' ', 'B', 'u', 'r', 'n', 't', ' ', 'l', 'u', 'n', 'g', 's', ' ', 's', 'o', 'u', 'r', ' ', 't', 'a', 's', 't', 'e', ' '], [' ', 'L', 'i', 'g', 'h', 't', 's', ' ', 'g', 'o', 'n', 'e', ' ', 'd', 'a', 'y', 's', ' ', 'e', 'n', 'd', ' '], [' ', 'S', 't', 'r', 'u', 'g', 'g', 'l', 'i', 'n', 'g', ' ', 't', 'o', ' ', 'p', 'a', 'y', ' ', 'r', 'e', 'n', 't', ' '], [' ', 'L', 'o', 'n', 'g', ' ', 'n', 'i', 'g', 'h', 't', 's', ' ', 's', 't', 'r', 'a', 'n', 'g', 'e', ' ', 'm', 'e', 'n', ' '], [' ', 'A', 'n', 'd', ' ', 't', 'h', 'e', 'y', ' ', 's', 'a', 'y', ' '], [' ', 'S', 'h', 'e', 's', ' ', 'i', 'n', ' ', 't', 'h', 'e', ' ', 'c', 'l', 'a', 's', 's', ' ', 'a', ' ', 't', 'e', 'a', 'm', ' '], [' ', 'S', 't', 'u', 'c', 'k', ' ', 'i', 'n', ' ', 'h', 'e', 'r', ' ', 'd', 'a', 'y', 'd', 'r', 'e', 'a', 'm', ' '], [' ', 'B', 'e', 'e', 'n', ' ', 't', 'h', 'i', 's', ' ', 'w', 'a', 'y', ' ', 's', 'i', 'n', 'c', 'e', ' ', '1', '8', ' '], [' ', 'B', 'u', 't', ' ', 'l', 'a', 't', 'e', 'l', 'y', ' ', 'h', 'e', 'r', ' ', 'f', 'a', 'c', 'e', ' ', 's', 'e', 'e', 'm', 's', ' ', ' '], [' ', 'S', 'l', 'o', 'w', 'l', 'y', ' ', 's', 'i', 'n', 'k', 'i', 'n', 'g', ' ', 'w', 'a', 's', 't', 'i', 'n', 'g', ' '], [' ', 'C', 'r', 'u', 'm', 'b', 'l', 'i', 'n', 'g', ' ', 'l', 'i', 'k', 'e', ' ', 'p', 'a', 's', 't', 'r', 'i', 'e', 's', ' '], [' ', 'T', 'h', 'e', 'y', ' ', 's', 'c', 'r', 'e', 'a', 'm', ' '], [' ', 'T', 'h', 'e', ' ', 'w', 'o', 'r', 's', 't', ' ', 't', 'h', 'i', 'n', 'g', 's', ' ', 'i', 'n', ' ', 'l', 'i', 'f', 'e', ' ', 'c', 'o', 'm', 'e', ' ', 'f', 'r', 'e', 'e', ' ', 't', 'o', ' ', 'u', 's', ' '], [' ', 'C', 'a', 'u', 's', 'e', ' ', 'w', 'e', 'r', 'e', ' ', 'j', 'u', 's', 't', ' ', 'u', 'n', 'd', 'e', 'r', ' ', 't', 'h', 'e', ' ', 'u', 'p', 'p', 'e', 'r', 'h', 'a', 'n', 'd', ' '], [' ', 'A', 'n', 'd', ' ', 'g', 'o', ' ', 'm', 'a', 'd', ' ', 'f', 'o', 'r', ' ', 'a', ' ', 'c', 'o', 'u', 'p', 'l', 'e', ' ', 'g', 'r', 'a', 'm', 's', ' '], [' ', 'A', 'n', 'd', ' ', 's', 'h', 'e', ' ', 'd', 'o', 'n', 't', ' ', 'w', 'a', 'n', 't', ' ', 't', 'o', ' ', 'g', 'o', ' ', 'o', 'u', 't', 's', 'i', 'd', 'e', ' ', 't', 'o', 'n', 'i', 'g', 'h', 't', ' '], [' ', 'A', 'n', 'd', ' ', 'i', 'n', ' ', 'a', ' ', 'p', 'i', 'p', 'e', ' ', 's', 'h', 'e', ' ', 'f', 'l', 'i', 'e', 's', ' ', 't', 'o', ' ', 't', 'h', 'e', ' ', 'm', 'o', 't', 'h', 'e', 'r', 'l', 'a', 'n', 'd', ' '], [' ', 'O', 'r', ' ', 's', 'e', 'l', 'l', 's', ' ', 'l', 'o', 'v', 'e', ' ', 't', 'o', ' ', 'a', 'n', 'o', 't', 'h', 'e', 'r', ' ', 'm', 'a', 'n', ' '], [' ', 'I', 't', 's', ' ', 't', 'o', 'o', ' ', 'c', 'o', 'l', 'd', ' ', 'o', 'u', 't', 's', 'i', 'd', 'e', ' '], [' ', 'F', 'o', 'r', ' ', 'a', 'n', 'g', 'e', 'l', 's', ' ', 't', 'o', ' ', 'f', 'l', 'y', ' '], [' ', 'A', 'n', 'g', 'e', 'l', 's', ' ', 't', 'o', ' ', 'f', 'l', 'y', ' '], [' ', 'R', 'i', 'p', 'p', 'e', 'd', ' ', 'g', 'l', 'o', 'v', 'e', 's', ' ', 'r', 'a', 'i', 'n', 'c', 'o', 'a', 't', ' '], [' ', 'T', 'r', 'i', 'e', 'd', ' ', 't', 'o', ' ', 's', 'w', 'i', 'm', ' ', 's', 't', 'a', 'y', ' ', 'a', 'f', 'l', 'o', 'a', 't', ' '], [' ', 'D', 'r', 'y', ' ', 'h', 'o', 'u', 's', 'e', ' ', 'w', 'e', 't', ' ', 'c', 'l', 'o', 't', 'h', 'e', 's', ' '], [' ', 'L', 'o', 'o', 's', 'e', ' ', 'c', 'h', 'a', 'n', 'g', 'e', ' ', 'b', 'a', 'n', 'k', ' ', 'n', 'o', 't', 'e', 's', ' '], [' ', 'W', 'e', 'a', 'r', 'y', 'e', 'y', 'e', 'd', ' ', 'd', 'r', 'y', ' ', 't', 'h', 'r', 'o', 'a', 't', ' '], [' ', 'C', 'o', 'o', 'l', ' ', 'g', 'i', 'r', 'l', ' ', 'n', 'o', ' ', 'p', 'h', 'o', 'n', 'e', ' '], [' ', 'A', 'n', 'd', ' ', 't', 'h', 'e', 'y', ' ', 's', 'a', 'y', ' '], [' ', 'S', 'h', 'e', 's', ' ', 'i', 'n', ' ', 't', 'h', 'e', ' ', 'c', 'l', 'a', 's', 's', ' ', 'a', ' ', 't', 'e', 'a', 'm', ' '], [' ', 'S', 't', 'u', 'c', 'k', ' ', 'i', 'n', ' ', 'h', 'e', 'r', ' ', 'd', 'a', 'y', 'd', 'r', 'e', 'a', 'm', ' '], [' ', 'B', 'e', 'e', 'n', ' ', 't', 'h', 'i', 's', ' ', 'w', 'a', 'y', ' ', 's', 'i', 'n', 'c', 'e', ' ', '1', '8', ' '], [' ', 'B', 'u', 't', ' ', 'l', 'a', 't', 'e', 'l', 'y', ' ', 'h', 'e', 'r', ' ', 'f', 'a', 'c', 'e', ' ', 's', 'e', 'e', 'm', 's', ' '], [' ', 'S', 'l', 'o', 'w', 'l', 'y', ' ', 's', 'i', 'n', 'k', 'i', 'n', 'g', ' ', 'w', 'a', 's', 't', 'i', 'n', 'g', ' '], [' ', 'C', 'r', 'u', 'm', 'b', 'l', 'i', 'n', 'g', ' ', 'l', 'i', 'k', 'e', ' ', 'p', 'a', 's', 't', 'r', 'i', 'e', 's', ' '], [' ', 'A', 'n', 'd', ' ', 't', 'h', 'e', 'y', ' ', 's', 'c', 'r', 'e', 'a', 'm', ' '], [' ', 'T', 'h', 'e', ' ', 'w', 'o', 'r', 's', 't', ' ', 't', 'h', 'i', 'n', 'g', 's', ' ', 'i', 'n', ' ', 'l', 'i', 'f', 'e', ' ', 'c', 'o', 'm', 'e', ' ', 'f', 'r', 'e', 'e', ' ', 't', 'o', ' ', 'u', 's', ' '], [' ', 'C', 'a', 'u', 's', 'e', ' ', 'w', 'e', 'r', 'e', ' ', 'j', 'u', 's', 't', ' ', 'u', 'n', 'd', 'e', 'r', ' ', 't', 'h', 'e', ' ', 'u', 'p', 'p', 'e', 'r', 'h', 'a', 'n', 'd', ' '], [' ', 'A', 'n', 'd', ' ', 'g', 'o', ' ', 'm', 'a', 'd', ' ', 'f', 'o', 'r', ' ', 'a', ' ', 'c', 'o', 'u', 'p', 'l', 'e', ' ', 'g', 'r', 'a', 'm', 's', ' '], [' ', 'B', 'u', 't', ' ', 's', 'h', 'e', ' ', 'd', 'o', 'n', 't', ' ', 'w', 'a', 'n', 't', ' ', 't', 'o', ' ', 'g', 'o', ' ', 'o', 'u', 't', 's', 'i', 'd', 'e', ' ', 't', 'o', 'n', 'i', 'g', 'h', 't', ' '], [' ', 'A', 'n', 'd', ' ', 'i', 'n', ' ', 'a', ' ', 'p', 'i', 'p', 'e', ' ', 's', 'h', 'e', ' ', 'f', 'l', 'i', 'e', 's', ' ', 't', 'o', ' ', 't', 'h', 'e', ' ', 'm', 'o', 't', 'h', 'e', 'r', 'l', 'a', 'n', 'd', ' '], [' ', 'O', 'r', ' ', 's', 'e', 'l', 'l', 's', ' ', 'l', 'o', 'v', 'e', ' ', 't', 'o', ' ', 'a', 'n', 'o', 't', 'h', 'e', 'r', ' ', 'm', 'a', 'n', ' '], [' ', 'I', 't', 's', ' ', 't', 'o', 'o', ' ', 'c', 'o', 'l', 'd', ' ', 'o', 'u', 't', 's', 'i', 'd', 'e', ' '], [' ', 'F', 'o', 'r', ' ', 'a', 'n', 'g', 'e', 'l', 's', ' ', 't', 'o', ' ', 'f', 'l', 'y', ' '], [' ', 'A', 'n', ' ', 'a', 'n', 'g', 'e', 'l', ' ', 'w', 'i', 'l', 'l', ' ', 'd', 'i', 'e', ' '], [' ', 'C', 'o', 'v', 'e', 'r', 'e', 'd', ' ', 'i', 'n', ' ', 'w', 'h', 'i', 't', 'e', ' '], [' ', 'C', 'l', 'o', 's', 'e', 'd', ' ', 'e', 'y', 'e', ' '], [' ', 'A', 'n', 'd', ' ', 'h', 'o', 'p', 'i', 'n', 'g', ' ', 'f', 'o', 'r', ' ', 'a', ' ', 'b', 'e', 't', 't', 'e', 'r', ' ', 'l', 'i', 'f', 'e', ' '], [' ', 'T', 'h', 'i', 's', ' ', 't', 'i', 'm', 'e', ' ', 'w', 'e', 'l', 'l', ' ', 'f', 'a', 'd', 'e', ' ', 'o', 'u', 't', ' ', 't', 'o', 'n', 'i', 'g', 'h', 't', ' '], [' ', 'S', 't', 'r', 'a', 'i', 'g', 'h', 't', ' ', 'd', 'o', 'w', 'n', ' ', 't', 'h', 'e', ' ', 'l', 'i', 'n', 'e', ' '], [' ', 'A', 'n', 'd', ' ', 't', 'h', 'e', 'y', ' ', 's', 'a', 'y', ' '], [' ', 'S', 'h', 'e', 's', ' ', 'i', 'n', ' ', 't', 'h', 'e', ' ', 'c', 'l', 'a', 's', 's', ' ', 'a', ' ', 't', 'e', 'a', 'm', ' '], [' ', 'S', 't', 'u', 'c', 'k', ' ', 'i', 'n', ' ', 'h', 'e', 'r', ' ', 'd', 'a', 'y', 'd', 'r', 'e', 'a', 'm', ' '], [' ', 'B', 'e', 'e', 'n', ' ', 't', 'h', 'i', 's', ' ', 'w', 'a', 'y', ' ', 's', 'i', 'n', 'c', 'e', ' ', '1', '8', ' '], [' ', 'B', 'u', 't', ' ', 'l', 'a', 't', 'e', 'l', 'y', ' ', 'h', 'e', 'r', ' ', 'f', 'a', 'c', 'e', ' ', 's', 'e', 'e', 'm', 's', ' '], [' ', 'S', 'l', 'o', 'w', 'l', 'y', ' ', 's', 'i', 'n', 'k', 'i', 'n', 'g', ' ', 'w', 'a', 's', 't', 'i', 'n', 'g', ' '], [' ', 'C', 'r', 'u', 'm', 'b', 'l', 'i', 'n', 'g', ' ', 'l', 'i', 'k', 'e', ' ', 'p', 'a', 's', 't', 'r', 'i', 'e', 's', ' '], [' ', 'T', 'h', 'e', 'y', ' ', 's', 'c', 'r', 'e', 'a', 'm', ' '], [' ', 'T', 'h', 'e', ' ', 'w', 'o', 'r', 's', 't', ' ', 't', 'h', 'i', 'n', 'g', 's', ' ', 'i', 'n', ' ', 'l', 'i', 'f', 'e', ' ', 'c', 'o', 'm', 'e', ' ', 'f', 'r', 'e', 'e', ' ', 't', 'o', ' ', 'u', 's', ' '], [' ', 'A', 'n', 'd', ' ', 'w', 'e', 'r', 'e', ' ', 'a', 'l', 'l', ' ', 'u', 'n', 'd', 'e', 'r', ' ', 't', 'h', 'e', ' ', 'u', 'p', 'p', 'e', 'r', 'h', 'a', 'n', 'd', ' '], [' ', 'G', 'o', ' ', 'm', 'a', 'd', ' ', 'f', 'o', 'r', ' ', 'a', ' ', 'c', 'o', 'u', 'p', 'l', 'e', ' ', 'g', 'r', 'a', 'm', 's', ' '], [' ', 'A', 'n', 'd', ' ', 'w', 'e', ' ', 'd', 'o', 'n', 't', ' ', 'w', 'a', 'n', 't', ' ', 't', 'o', ' ', 'g', 'o', ' ', 'o', 'u', 't', 's', 'i', 'd', 'e', ' ', 't', 'o', 'n', 'i', 'g', 'h', 't', ' '], [' ', 'A', 'n', 'd', ' ', 'i', 'n', ' ', 'a', ' ', 'p', 'i', 'p', 'e', ' ', 'w', 'e', ' ', 'f', 'l', 'y', ' ', 't', 'o', ' ', 't', 'h', 'e', ' ', 'm', 'o', 't', 'h', 'e', 'r', 'l', 'a', 'n', 'd', ' '], [' ', 'O', 'r', ' ', 's', 'e', 'l', 'l', ' ', 'l', 'o', 'v', 'e', ' ', 't', 'o', ' ', 'a', 'n', 'o', 't', 'h', 'e', 'r', ' ', 'm', 'a', 'n', ' '], [' ', 'I', 't', 's', ' ', 't', 'o', 'o', ' ', 'c', 'o', 'l', 'd', ' ', 'o', 'u', 't', 's', 'i', 'd', 'e', ' '], [' ', 'F', 'o', 'r', ' ', 'a', 'n', 'g', 'e', 'l', 's', ' ', 't', 'o', ' ', 'f', 'l', 'y', ' '], [' ', 'A', 'n', 'g', 'e', 'l', 's', ' ', 't', 'o', ' ', 'f', 'l', 'y', ' '], [' ', 'T', 'o', ' ', 'f', 'l', 'y', ' ', 'f', 'l', 'y', ' '], [' ', 'F', 'o', 'r', ' ', 'a', 'n', 'g', 'e', 'l', 's', ' ', 't', 'o', ' ', 'f', 'l', 'y', ' ', 't', 'o', ' ', 'f', 'l', 'y', ' ', 't', 'o', ' ', 'f', 'l', 'y', ' '], [' ', 'A', 'n', 'g', 'e', 'l', 's', ' ', 't', 'o', ' ', 'd', 'i', 'e']]

## Joining a list of strings into one string

Now that we've turned the first character into an upper case, let's move onto the next step in our pseudocode: joining the strings.

<img width="300" src="https://drive.google.com/uc?export=view&id=1hjJHa0x_pEEZoXlxp9qX3SN4nOjnofVE">


One way of joining this list of characters into one string will be to use the **join()** method.

The **join()** method returns a string where a sequence of strings is joined by an identified separator. Let's look at the list of characters from our previous example:

```python
ed_sheeran = ['E', 'd', ' ', 'S', 'h', 'e', 'e', 'r', 'a', 'n']
```

To join this list into one string:

```python
"".join(ed_sheeran)
```

Printing this line would return:

```python
Ed Sheeran
```

The **""** is the separator separating each value in our results. Here, we've specified no separator. However, let's add our own separator:

```python
"[TEST]".join(ed_sheeran)
```

This would print:

```python
E[TEST]d[TEST] [TEST]s[TEST]h[TEST]e[TEST]e[TEST]r[TEST]a[TEST]n
```

We see that **[TEST]** is inserted in between each character in our list.

Now, let's join our list of characters into a string.


**Exercise**

<left><img width="100" src="https://drive.google.com/uc?export=view&id=1E8tR7B9YYUXsU_rddJAyq0FrM0MSelxZ"></left>

1. Use a list comprehension to loop through **ed_sheeran** and join each list of characters into a full string. 
  - Store this in **ed_sheeran**. 
  - Include an empty separator.
2. Join the **ed_sheeran** list into a full string using **str.join**.
  - Use **"\n"** as the separator.
  - Store the combined string in **ed_sheeran_full**.

In [17]:
# put your code here
ed_sheeran = [''.join(ed) for ed in ed_sheeran]
ed_sheeran_full = '\n'.join(ed_sheeran)
ed_sheeran_full

' White lips, pale face \n Breathing in snowflakes \n Burnt lungs sour taste \n Lights gone days end \n Struggling to pay rent \n Long nights strange men \n And they say \n Shes in the class a team \n Stuck in her daydream \n Been this way since 18 \n But lately her face seems  \n Slowly sinking wasting \n Crumbling like pastries \n They scream \n The worst things in life come free to us \n Cause were just under the upperhand \n And go mad for a couple grams \n And she dont want to go outside tonight \n And in a pipe she flies to the motherland \n Or sells love to another man \n Its too cold outside \n For angels to fly \n Angels to fly \n Ripped gloves raincoat \n Tried to swim stay afloat \n Dry house wet clothes \n Loose change bank notes \n Wearyeyed dry throat \n Cool girl no phone \n And they say \n Shes in the class a team \n Stuck in her daydream \n Been this way since 18 \n But lately her face seems \n Slowly sinking wasting \n Crumbling like pastries \n And they scream \n The worst things in life come free to us \n Cause were just under the upperhand \n And go mad for a couple grams \n But she dont want to go outside tonight \n And in a pipe she flies to the motherland \n Or sells love to another man \n Its too cold outside \n For angels to fly \n An angel will die \n Covered in white \n Closed eye \n And hoping for a better life \n This time well fade out tonight \n Straight down the line \n And they say \n Shes in the class a team \n Stuck in her daydream \n Been this way since 18 \n But lately her face seems \n Slowly sinking wasting \n Crumbling like pastries \n They scream \n The worst things in life come free to us \n And were all under the upperhand \n Go mad for a couple grams \n And we dont want to go outside tonight \n And in a pipe we fly to the motherland \n Or sell love to another man \n Its too cold outside \n For angels to fly \n Angels to fly \n To fly fly \n For angels to fly to fly to fly \n Angels to die'

## String Concatenation

In the previous screen, we joined our strings using the **join()** method. An alternative method is to use string concatenation. String concatenation is similar to the addition of two integers. Let's look at an example:

```python
ed = 'ed'
sheeran = 'sheeran'
```

To concatenate these strings:

```python
ed = 'ed'
sheeran = 'sheeran'

ed_sheeran = ed + sheeran
```

This would print:

```python
edsheeran
```

In relation to mutability, when we concatenate a string, the string will create a copy of itself and then add them together.

Wrapping up the fourth step of our pseudo-code, we've taught you two ways of combining a list of characters into a string. Which one do you use?

For now, use **join** when combining multiple values. If we're just making one concatenation, use **+**.


**Exercise**

<left><img width="100" src="https://drive.google.com/uc?export=view&id=1E8tR7B9YYUXsU_rddJAyq0FrM0MSelxZ"></left>

1. Create an empty string called **ed_sheeran_full**.
2. Loop through **ed_sheeran** add each line into **ed_sheeran_full**. Add a **\n** to the end of each line.

In [19]:
# put your code here
ed_sheeran_full = ''
for ed in ed_sheeran:
    ed_sheeran_full += ed +"\n"
ed_sheeran_full

' White lips, pale face \n Breathing in snowflakes \n Burnt lungs sour taste \n Lights gone days end \n Struggling to pay rent \n Long nights strange men \n And they say \n Shes in the class a team \n Stuck in her daydream \n Been this way since 18 \n But lately her face seems  \n Slowly sinking wasting \n Crumbling like pastries \n They scream \n The worst things in life come free to us \n Cause were just under the upperhand \n And go mad for a couple grams \n And she dont want to go outside tonight \n And in a pipe she flies to the motherland \n Or sells love to another man \n Its too cold outside \n For angels to fly \n Angels to fly \n Ripped gloves raincoat \n Tried to swim stay afloat \n Dry house wet clothes \n Loose change bank notes \n Wearyeyed dry throat \n Cool girl no phone \n And they say \n Shes in the class a team \n Stuck in her daydream \n Been this way since 18 \n But lately her face seems \n Slowly sinking wasting \n Crumbling like pastries \n And they scream \n The worst things in life come free to us \n Cause were just under the upperhand \n And go mad for a couple grams \n But she dont want to go outside tonight \n And in a pipe she flies to the motherland \n Or sells love to another man \n Its too cold outside \n For angels to fly \n An angel will die \n Covered in white \n Closed eye \n And hoping for a better life \n This time well fade out tonight \n Straight down the line \n And they say \n Shes in the class a team \n Stuck in her daydream \n Been this way since 18 \n But lately her face seems \n Slowly sinking wasting \n Crumbling like pastries \n They scream \n The worst things in life come free to us \n And were all under the upperhand \n Go mad for a couple grams \n And we dont want to go outside tonight \n And in a pipe we fly to the motherland \n Or sell love to another man \n Its too cold outside \n For angels to fly \n Angels to fly \n To fly fly \n For angels to fly to fly to fly \n Angels to die\n'

## Replacing Values In A String

Now that we've cleaned our lyrics, we can start creating the mad libs game. For step five, now, we'll need to replace the parts of speech tags with real words:

<img width="300" src="https://drive.google.com/uc?export=view&id=1rT_h6J_ZOi2J3UZgK0F_SGRDcW1nVnGD">

To create our mad libs, we'll need to write a function that replaces the specific parts of speech with the words we'd like to include. To replace specific parts of a string, we'll use the **replace()** method.

**replace()** allows us to identify the occurence of a string we'd like to replace with a new string. The syntax of **replace()** looks like this:

```python
str.replace(old, new)
```

Let's look at an example. Let's take our 'ed sheeran' string:

```python
ed_sheeran = 'ed sheeran'
```

Now, let's replace **"ed"** with **"bob"**:

```python
ed_sheeran.replace("ed","bob")
```

This would print:

```python
'bob sheeran'
```

Now, let's replace the nouns, verbs and adjectives!

**Exercise**

<left><img width="100" src="https://drive.google.com/uc?export=view&id=1E8tR7B9YYUXsU_rddJAyq0FrM0MSelxZ"></left>

1. Replace each of the following in **mad_libs_joined**:
  - {ADJ} with "stinky".
  - {NOUN} with "piano".
  - {AGE} with "99".
  - {NOUN_PLURAL} with "phones".
  - {VERB} with "crush".
  - {LOCATION} with "Antarctica".
  - {CELEBRITY} with "Beyonce".
2. Store each replacement into **mad_libs_joined** like this:

```python
mad_libs_joined = mad_libs_joined.replace("{PART}","new_word")
mad_libs_joined = mad_libs_joined.replace("{PART_2}","new_word_2")
```

In [20]:
mad_libs = [' {ADJ} {NOUN}, pale face ',
 ' Breathing in {NOUN} ',
 ' Burnt {NOUN} {ADJ} taste ',
 ' Lights gone days end ',
 ' Struggling to pay {NOUN} ',
 ' Long nights strange {NOUN} ',
 ' And they say ',
 ' Shes in the class a team ',
 ' Stuck in her {NOUN} ',
 ' Been this way since {AGE}',
 'But lately her {NOUN} seems  ',
 ' Slowly sinking wasting ',
 ' Crumbling like {NOUN_PLURAL} ',
 ' They {VERB} ',
 ' The worst things in life come free to us ',
 ' Cause were just under the upperhand ',
 ' And go mad for a couple {NOUN_PLURAL} ',
 ' And she dont want to go outside tonight ',
 ' And in a pipe she flies to the {LOCATION} ',
 ' Or sells love to {CELEBRITY} ',
 ' Its too cold outside ',
 ' For angels to {VERB} ',
 ' Angels to {VERB} ',
 ' Ripped {NOUN} raincoat ',
 ' Tried to {VERB} stay afloat ',
 ' {ADJ} house wet clothes ',
 ' Loose change bank notes ',
 ' Weary eyed {ADJ} throat ',
 ' Cool girl no phone ',
 ' And they say ',
 ' Shes in the class a team ',
 ' Stuck in her {NOUN} ',
 ' Been this way since {AGE} ',
 ' But lately her face seems ',
 ' Slowly sinking wasting ',
 ' Crumbling like {NOUN} ',
 ' And they {VERB} ',
 ' The worst things in life come free to us ',
 ' Cause were just under the {NOUN} ',
 ' And go mad for a couple grams ',
 ' But she dont want to go outside tonight ',
 ' And in a pipe she flies to the {LOCATION} ',
 ' Or sells love to another man ',
 ' Its too cold outside ',
 ' For angels to {VERB} ',
 ' An angel will die ',
 ' Covered in white ',
 ' Closed eye ',
 ' And hoping for a better life ',
 ' This time well fade out tonight ',
 ' Straight down the line ',
 ' And they {VERB} ',
 ' Shes in the class a team ',
 ' Stuck in her {NOUN} ',
 ' Been this way since {AGE} ',
 ' But lately her face seems ',
 ' Slowly sinking wasting ',
 ' Crumbling like pastries ',
 ' They {VERB} ',
 ' The worst things in life come free to us ',
 ' And were all under the upperhand ',
 ' Go mad for a couple grams ',
 ' And we dont want to go outside tonight ',
 ' And in a pipe we {VERB} to the motherland ',
 ' Or {VERB} love to another man ',
 ' Its too cold outside ',
 ' For angels to fly ',
 ' Angels to fly ',
 ' To fly fly ',
 ' For angels to {VERB} to {VERB} to {VERB} ',
 ' Angels to {VERB}']

mad_libs_joined = "\n".join(mad_libs)

#put your code here
mad_libs_joined = mad_libs_joined.replace("{ADJ}","stinky")
mad_libs_joined = mad_libs_joined.replace("{NOUN}","piano")
mad_libs_joined = mad_libs_joined.replace("{AGE}","99")
mad_libs_joined = mad_libs_joined.replace("{NOUN_PLURAL}","phones")
mad_libs_joined = mad_libs_joined.replace("{VERB}","crush")
mad_libs_joined = mad_libs_joined.replace("{LOCATION}","Antarctica")
mad_libs_joined = mad_libs_joined.replace("{CELEBRITY}","Beyonce")
mad_libs_joined

' stinky piano, pale face \n Breathing in piano \n Burnt piano stinky taste \n Lights gone days end \n Struggling to pay piano \n Long nights strange piano \n And they say \n Shes in the class a team \n Stuck in her piano \n Been this way since 99\nBut lately her piano seems  \n Slowly sinking wasting \n Crumbling like phones \n They crush \n The worst things in life come free to us \n Cause were just under the upperhand \n And go mad for a couple phones \n And she dont want to go outside tonight \n And in a pipe she flies to the Antarctica \n Or sells love to Beyonce \n Its too cold outside \n For angels to crush \n Angels to crush \n Ripped piano raincoat \n Tried to crush stay afloat \n stinky house wet clothes \n Loose change bank notes \n Weary eyed stinky throat \n Cool girl no phone \n And they say \n Shes in the class a team \n Stuck in her piano \n Been this way since 99 \n But lately her face seems \n Slowly sinking wasting \n Crumbling like piano \n And they crush \n The worst things in life come free to us \n Cause were just under the piano \n And go mad for a couple grams \n But she dont want to go outside tonight \n And in a pipe she flies to the Antarctica \n Or sells love to another man \n Its too cold outside \n For angels to crush \n An angel will die \n Covered in white \n Closed eye \n And hoping for a better life \n This time well fade out tonight \n Straight down the line \n And they crush \n Shes in the class a team \n Stuck in her piano \n Been this way since 99 \n But lately her face seems \n Slowly sinking wasting \n Crumbling like pastries \n They crush \n The worst things in life come free to us \n And were all under the upperhand \n Go mad for a couple grams \n And we dont want to go outside tonight \n And in a pipe we crush to the motherland \n Or crush love to another man \n Its too cold outside \n For angels to fly \n Angels to fly \n To fly fly \n For angels to crush to crush to crush \n Angels to crush'

## Replacing Values In A String Using Formatter

An alternative to using **replace()** would be to use the **format()** function within the string class. **format()** is a built-in string method, where we can specify the location of what we'd like to replace. Documentation here. Here's what the syntax looks like:

```python
"hello {0}".format("world")
```

This would print:

```python
"Hello World"
```

0 corresponds to the first argument within the **format()** method. Anytime we want to use **format()**, to denote the location of an argument, we use brackets **{0}** around the argument name. If we wanted to extend this string:

```python
"hello {0}. I'm doing {1}".format("world", "well")
```

Here's what the arguments correspond to:

<img width="500" src="https://drive.google.com/uc?export=view&id=1-YibjCt1CU4uAFC6ygCR4pRf2teh413H">


If we used the 0 twice:

```python
"hello {0}. I'm doing {0}".format("world", "well")
```

<img width="500" src="https://drive.google.com/uc?export=view&id=1RaCe8A6-6zb-Gf1u9SOwC0D-pKdn9OB-">

This would print:

```python
"hello world. I'm doing world"
```

Let's format a basic string!


**Exercise**

<left><img width="100" src="https://drive.google.com/uc?export=view&id=1E8tR7B9YYUXsU_rddJAyq0FrM0MSelxZ"></left>


1. Replace **"lips"** and **"face"** with the new nouns: **"hat"**, **"skin"**.
2. Store the resulting object in **first_line**.

In [21]:
"White lips, pale face"

# put your code here
first_line = "White lips, pale face".replace("lips", "hat").replace("face", "skin")
first_line

'White hat, pale skin'

## Formatting our song lyrics

Now that we understand the basics of **format()**, let's expand this for the entire song. However, using the current numerical way of formatting **(0,1 ....)** wouldn't make sense for our mad libs. We'd need to know the part of speech associated with that word. As a result, we'll need to format using a specified parameter.

Rather than use 0 and 1 we can specify a parameter within format. A parameter allows us to replace any occurence of that parameter within our string. Let's look at an example. Here's our original:

```python
"hello {0}. I'm doing {1}".format("world", "well")
```

If we changed this using a parameter:

```python
"hello {NOUN}. I'm doing {ADJ}".format(NOUN="world", ADJ="well")
```

<img width="600" src="https://drive.google.com/uc?export=view&id=1a4rKjX-G9CwcdPGwQ2hAI_FaklVyweVG">

**format()** will look for every occurence of the parameter specified in our brackets. By defining a specific parameter, we can then format our string by placing that parameter between brackets. Let's replace the parts of speech for the entire song.



**Exercise**

<left><img width="100" src="https://drive.google.com/uc?export=view&id=1E8tR7B9YYUXsU_rddJAyq0FrM0MSelxZ"></left>

1. Within **mad_libs**, replace the parts of speech using **str.format()**:
  - {ADJ} with "strong".
  - {NOUN} with "piano".
  - {AGE} with "99".
  - {NOUN_PLURAL} with "phones".
  - {VERB} with "smash".
  - {LOCATION} with "Antarctica".
  - {CELEBRITY} with "Beyonce".
2. Store the results in **final**.

In [23]:
# put your code here
mad_libs = "\n".join(mad_libs)
final = mad_libs.format(ADJ="strong", NOUN="piano", AGE=99, NOUN_PLURAL="phones", VERB="smash", LOCATION="Antartica", CELEBRITY="Beyonce")
final

' strong piano, pale face \n Breathing in piano \n Burnt piano strong taste \n Lights gone days end \n Struggling to pay piano \n Long nights strange piano \n And they say \n Shes in the class a team \n Stuck in her piano \n Been this way since 99\nBut lately her piano seems  \n Slowly sinking wasting \n Crumbling like phones \n They smash \n The worst things in life come free to us \n Cause were just under the upperhand \n And go mad for a couple phones \n And she dont want to go outside tonight \n And in a pipe she flies to the Antartica \n Or sells love to Beyonce \n Its too cold outside \n For angels to smash \n Angels to smash \n Ripped piano raincoat \n Tried to smash stay afloat \n strong house wet clothes \n Loose change bank notes \n Weary eyed strong throat \n Cool girl no phone \n And they say \n Shes in the class a team \n Stuck in her piano \n Been this way since 99 \n But lately her face seems \n Slowly sinking wasting \n Crumbling like piano \n And they smash \n The worst things in life come free to us \n Cause were just under the piano \n And go mad for a couple grams \n But she dont want to go outside tonight \n And in a pipe she flies to the Antartica \n Or sells love to another man \n Its too cold outside \n For angels to smash \n An angel will die \n Covered in white \n Closed eye \n And hoping for a better life \n This time well fade out tonight \n Straight down the line \n And they smash \n Shes in the class a team \n Stuck in her piano \n Been this way since 99 \n But lately her face seems \n Slowly sinking wasting \n Crumbling like pastries \n They smash \n The worst things in life come free to us \n And were all under the upperhand \n Go mad for a couple grams \n And we dont want to go outside tonight \n And in a pipe we smash to the motherland \n Or smash love to another man \n Its too cold outside \n For angels to fly \n Angels to fly \n To fly fly \n For angels to smash to smash to smash \n Angels to smash'

# Date Operations

- How to use the datetime module
- How to convert a string into a date object
- How to extract month, day, year from date objects

## Introduction

In the previous section we discovered that Ed Sheeran was the dominant artist of 2017. However, as a budding Data Analyst or Data Scientist, we should always maintain a healthy degree of skepticism towards our initial results. We should always ask additional questions to either validate, invalidate or better understand our results. Some additional questions we might ask:

- What factors could be influencing our results?
- Within these factors, which have the highest degree of influence on our results?
- How could our initial approach bias our results?

Whenever we're performing an analysis, a common influence on our results is **time**. Time often guides our own behavior. We tend to shop more during the month of December compared to August. During winter time, we likely use the heater more. We're also more likely to use the internet during the daytime for work rather than 3am.

A dataset often reflects changes with respect to time. For example, we might conclude that Ed Sheeran was the dominant artist of 2017. However, our results could be heavily influenced by spikes in one or two months:

<img width="500" src="https://drive.google.com/uc?export=view&id=1qC7CqtIMY5cDfXrQFhpoa1MCwxnuNU-t">


A huge spike in two months, could drastically skew our conclusion. There's a possibility that Spotify users listen to Ed Sheeran more on certain months of the year than others. Perhaps, Ed Sheeran isn't the most popular artist in January to March, but is extremely popular during the summer months. We don't know.

To better understand our results with respect to time, we'll be answering the following question in this mission:

- **Who is the dominant artist for each month of the year?**

We'll be working with a subset of the [Spotify WorldWide Daily Song Ranking dataset](https://www.kaggle.com/edumucelli/spotifys-worldwide-daily-song-ranking). This subset contains the global rankings (**Region** column filtered to **"global"**) only from the original dataset. We'll explore:

- How to use the datetime module to add a date component to our analysis
- How to convert strings to date objects
- How to extract different components of time from the date objects

Let's get started!


**Exercise**

<left><img width="100" src="https://drive.google.com/uc?export=view&id=1E8tR7B9YYUXsU_rddJAyq0FrM0MSelxZ"></left>

1. Read **"global_rankings.csv"** into a list named **music**.

In [103]:
# put your code here
import csv

music = list(csv.reader(open("global_rankings.csv","r", encoding='utf8')))
print(music)

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)

## Using the datetime module

Looking at the first row of our data, notice that the date column is the second to last column, with an index of -2:

```python
[['Position', 'Track Name', 'Artist', 'Streams', 'URL', 'Date', 'Region'],
 ['1', 'Reggaetón Lento (Bailemos)', 'CNCO','19272','https://open.spotify .......','2017-01-01','ec'],
```
 
 Let's index into the first track(index 1) and extract the date column(index -2):

```python
print(music[1][-2])
```

This would print:

```python
2017-01-01
```

Then, if we called type on this:

```python
print(type(music[1][-2]))
```

This would print:

```python
class 'str'
```

Currently, our date is a string type. To answer our initial question, we'll need to extract the month out of our string. One way of doing this, would be to split this string into a list, extract the month string and convert the month to an int:

```python
date = "2017-01-01"
date = date.split("-")
date = [int(d) for d in date]
day = date[-1]
```

Rather than extract the month manually, we can use the datetime module. The [datetime](https://docs.python.org/3/library/datetime.html) module supplies classes for manipulating dates and times. We'll learn about classes in the next mission. For now, think of classes as a bundle of methods and objects used for a specific purpose.

The datetime module contains the following classes:

- **time** - Represents time of day. To import:

```python
from datetime import time
```

- **date** - Represents a date in an idealized calendar. To import:

```python
from datetime import date
```

- **datetime** - Represents month, day, dayofweek, year etc. Combines both **time** class and **date** class. To import:

```python
from datetime import datetime
```

- **timedelta** - Represents duration of time, difference between two dates. To import:

```python
from datetime import timedelta
```

Since the **datetime** class encapsulates both **time** and **date**, we'll be using the **datetime** class in this lesson. The methods of the **datetime** class and **time**, **date** classes are generally very similar.

Returning back to our over-arching questions, **Who is the dominant artist for each month of the year?** , we could use the **datetime** class to extract the **month** out from our dates. But before we extract the month from our dates, we'll need to understand how to use a datetime object. A **datetime** object represents a single point in time. Here's the default formatting for a datetime object:

```python
datetime(YEAR, MONTH, DAYS, HOUR, MINUTE)
```

Replacing **YEAR**,**MONTH** and **DAYS** with values:

```python
datetime(2017, 1, 13, 5, 43)
```

This would translate to 5:43AM on January 13th, 2017. If we were to print our object, the interpreter would return:

```python
datetime.datetime(2017, 1, 13, 5, 43)
```

If we wanted to create an object that took place in the afternoon, let's say 5:43 PM, we'd have to write 17 as the hour. This is known as the 24 hour clock:

```python
datetime(2017, 1, 13, 17, 43)
```

Let's create our own datetime object!


**Exercise**

<left><img width="100" src="https://drive.google.com/uc?export=view&id=1E8tR7B9YYUXsU_rddJAyq0FrM0MSelxZ"></left>

1. Import the **datetime** function from the **datetime** library.
2. Create a datetime object for the following:
  - 12:43PM, January 27th, 1965. Store in **jan_27_1965**
  - 1:43AM, August 3rd, 1972. Store in **aug_3_1972**
  - 3:12PM, October 31st, 2000. Store in **oct_31_2000**
  - 7:30AM, March 2nd, 2017. Store in **mar_2_2017**

In [26]:
# put your code here
from datetime import datetime

jan_27_1965 = datetime(1965,1,27,12,43)
aug_3_1972 = datetime(1972,8,3,1,43)
oct_31_2000 = datetime(2000,10,31,3,12)
mar_2_2017 = datetime(2017,3,2,7,30)
jan_27_1965

datetime.datetime(1965, 1, 27, 12, 43)

## Creating a datetime object using a string

Because our date is currently a string, we'll need to convert this string into a datetime object:

<img width="500" src="https://drive.google.com/uc?export=view&id=147NuRnVtn0ZynIemQTJ_B41mDH9_GzGF">


To convert a string into a datetime object, we'll use a method within the **datetime** class called **strptime()**. Documentation [here](https://docs.python.org/3/library/datetime.html#strftime-strptime-behavior).

**strptime()** is a method that converts a string into a datetime object. Within **strptime()**, we must identify two arguments:

- The string we'd like to convert into a datetime object.
- The format of the input string so **strptime**. So the method can identify which parts of the string is the day, month and year.

For example:

```python
date = "01/01/2017"
datetime.strptime(date, "%m/%d/%Y")
```

Here, we have identified the day, January 1st, 2017. **date** goes in as the first argument. The second argument **"%m/%d/%Y"**, we've identified the formatting of our string:

<center>
<img width="100" src="https://drive.google.com/uc?export=view&id=1x1USpXCu68dEQ1ViL5GesbjXDvJbEiVm">
</center>


When converting our string, **"%m/%d/%Y"** is a combination of formatting codes. Formatting codes comes from the C language. You can see all the formatting codes [here](https://docs.python.org/3/library/datetime.html#strftime-strptime-behavior). Here are the ones we'll be using:

<center>
<img width="500" src="https://drive.google.com/uc?export=view&id=1GeH_BWLh9HYtVBZ8u1c08glKA5WW8rGN">
</center>


Remember, when we're using a four digit year, use a capital **Y**, not a lowercase **y**.

Now, let's say we wanted to convert our date **May 2nd, 2017** into a **datetime** object:

```python
date = "05-02-2017"
```

How would we specify the formatting codes within **strptime()**? The specific codes wouldn't change, but the order of the codes would match the format of the string:

```python
date = "05-02-2017"
datetime.strptime(date, "%m-%d-%Y")
```

**Exercise**

<left><img width="100" src="https://drive.google.com/uc?export=view&id=1E8tR7B9YYUXsU_rddJAyq0FrM0MSelxZ"></left>


1. Convert the following strings into datetime objects using **datetime.strptime()**:
  - "6-02-2008" (June 2nd, 2008). Store in variable called **jun_2_08**. 
  - "7?15?2001" (July 15, 2001). Store in variable called **jul_15_01**. 
  - "12--30--2010" (December 30, 2010). Store in variable called **dec_20_08**.

In [29]:
# put your code here
jun_2_08 = datetime.strptime("6-02-2008", "%m-%d-%Y")
jul_15_01 = datetime.strptime("7?15?2001", "%m?%d?%Y")
dec_20_08 = datetime.strptime("12--30--2010", "%m--%d--%Y")
jul_15_01

datetime.datetime(2001, 7, 15, 0, 0)

## Converting the string column into a datetime column

Now that we understand how to convert strings into datetime objects, let's convert our column of string dates into a datetime object.

**Exercise**

<left><img width="100" src="https://drive.google.com/uc?export=view&id=1E8tR7B9YYUXsU_rddJAyq0FrM0MSelxZ"></left>


1. To convert the entire column:

  - Write a function called **string_to_date()** that accepts **music** as an argument.
    - Loop through **music**.
      - Replace the string value with a datetime object using **datetime.strptime()**.
      - When using **strptime**, make sure the formatting codes match the string.
      - Append the new row to **add_date**.
  - Return the new list of datetime values outside of the loop.
2. Call the **string_to_date()** function on **music** and store this in **cleaned_music**.

In [104]:
# put your code here
def string_to_date(music):
    for m in music[1:]:
        m.append(datetime.strptime(m[5], "%Y-%m-%d"))
    return music[1:]
cleaned_music = string_to_date(music)
cleaned_music[:5]

[['1',
  'Starboy',
  'The Weeknd',
  '3135625',
  'https://open.spotify.com/track/5aAx2yezTd8zXrkmtKl66Z',
  '2017-01-01',
  'global',
  datetime.datetime(2017, 1, 1, 0, 0)],
 ['2',
  'Closer',
  'The Chainsmokers',
  '3015525',
  'https://open.spotify.com/track/7BKLCZ1jbUBVqRi2FVlTVw',
  '2017-01-01',
  'global',
  datetime.datetime(2017, 1, 1, 0, 0)],
 ['3',
  'Let Me Love You',
  'DJ Snake',
  '2545384',
  'https://open.spotify.com/track/4pdPtRcBmOSQDlJ3Fk945m',
  '2017-01-01',
  'global',
  datetime.datetime(2017, 1, 1, 0, 0)],
 ['4',
  'Rockabye (feat. Sean Paul & Anne-Marie)',
  'Clean Bandit',
  '2356604',
  'https://open.spotify.com/track/5knuzwU65gJK7IF5yJsuaW',
  '2017-01-01',
  'global',
  datetime.datetime(2017, 1, 1, 0, 0)],
 ['5',
  'One Dance',
  'Drake',
  '2259887',
  'https://open.spotify.com/track/1xznGGDReH1oQq0xzbwXa3',
  '2017-01-01',
  'global',
  datetime.datetime(2017, 1, 1, 0, 0)]]

## Extracting the month from the date object

Now that we've converted our strings to datetime objects, we can see the power of datetime objects. The datetime class has an assortment of methods for different use cases. Here are a few useful ones:

<img width="500" src="https://drive.google.com/uc?export=view&id=1XY_LQf1XeoyB2RatuFgabdRxVkvKv9Um">

You can see the list of all the methods for the datetime class [here](https://docs.python.org/3/library/datetime.html).

To use a method, we'll use the dot notation. For example, let's extract the year from 12:43pm January 17th, 1965

```python
Jan_27_1965 = datetime(2017, 1, 27, 12, 43)

print(Jan_27_1965.year)
```

This would print:

```python
2017
```

Let's extract the month out of our datetime column!

**Exercise**

<left><img width="100" src="https://drive.google.com/uc?export=view&id=1E8tR7B9YYUXsU_rddJAyq0FrM0MSelxZ"></left>


1. Write a function called **get_month()** that extracts the **month** from our datetime object.
  - The function should take in **cleaned_music** as an argument.
  - The function should add an additional column to our dataset containing the month.
2. Call the **get_month()** function on **cleaned_music** and assign the result in **add_month**.

In [105]:
# put your code here
def get_month(music):
    for m in music:
        m.append(m[-1].month)
    return music
add_month = get_month(cleaned_music)
add_month[:5]

[['1',
  'Starboy',
  'The Weeknd',
  '3135625',
  'https://open.spotify.com/track/5aAx2yezTd8zXrkmtKl66Z',
  '2017-01-01',
  'global',
  datetime.datetime(2017, 1, 1, 0, 0),
  1],
 ['2',
  'Closer',
  'The Chainsmokers',
  '3015525',
  'https://open.spotify.com/track/7BKLCZ1jbUBVqRi2FVlTVw',
  '2017-01-01',
  'global',
  datetime.datetime(2017, 1, 1, 0, 0),
  1],
 ['3',
  'Let Me Love You',
  'DJ Snake',
  '2545384',
  'https://open.spotify.com/track/4pdPtRcBmOSQDlJ3Fk945m',
  '2017-01-01',
  'global',
  datetime.datetime(2017, 1, 1, 0, 0),
  1],
 ['4',
  'Rockabye (feat. Sean Paul & Anne-Marie)',
  'Clean Bandit',
  '2356604',
  'https://open.spotify.com/track/5knuzwU65gJK7IF5yJsuaW',
  '2017-01-01',
  'global',
  datetime.datetime(2017, 1, 1, 0, 0),
  1],
 ['5',
  'One Dance',
  'Drake',
  '2259887',
  'https://open.spotify.com/track/1xznGGDReH1oQq0xzbwXa3',
  '2017-01-01',
  'global',
  datetime.datetime(2017, 1, 1, 0, 0),
  1]]

## Extracting the day from the date object

Similar to the previous screen, let's also extract the day of the month!


**Exercise**

<left><img width="100" src="https://drive.google.com/uc?export=view&id=1E8tR7B9YYUXsU_rddJAyq0FrM0MSelxZ"></left>


1. Write a function called **get_day()** that extracts the day of the month from our datetime object.
  - The function should take in **cleaned_music** as an argument.
  - The function should add an additional column to our dataset containing the day and return **cleaned_music**.
2. Call the **get_day()** function on **add_month** and store the result in **add_day**.

In [106]:
# put your code here
def get_day(music):
    for m in music:
        m.append(m[-2].day)
    return music
add_day = get_day(add_month)
add_day[:5]

[['1',
  'Starboy',
  'The Weeknd',
  '3135625',
  'https://open.spotify.com/track/5aAx2yezTd8zXrkmtKl66Z',
  '2017-01-01',
  'global',
  datetime.datetime(2017, 1, 1, 0, 0),
  1,
  1],
 ['2',
  'Closer',
  'The Chainsmokers',
  '3015525',
  'https://open.spotify.com/track/7BKLCZ1jbUBVqRi2FVlTVw',
  '2017-01-01',
  'global',
  datetime.datetime(2017, 1, 1, 0, 0),
  1,
  1],
 ['3',
  'Let Me Love You',
  'DJ Snake',
  '2545384',
  'https://open.spotify.com/track/4pdPtRcBmOSQDlJ3Fk945m',
  '2017-01-01',
  'global',
  datetime.datetime(2017, 1, 1, 0, 0),
  1,
  1],
 ['4',
  'Rockabye (feat. Sean Paul & Anne-Marie)',
  'Clean Bandit',
  '2356604',
  'https://open.spotify.com/track/5knuzwU65gJK7IF5yJsuaW',
  '2017-01-01',
  'global',
  datetime.datetime(2017, 1, 1, 0, 0),
  1,
  1],
 ['5',
  'One Dance',
  'Drake',
  '2259887',
  'https://open.spotify.com/track/1xznGGDReH1oQq0xzbwXa3',
  '2017-01-01',
  'global',
  datetime.datetime(2017, 1, 1, 0, 0),
  1,
  1]]

## Grouping and aggregating our data

Now, that we extracted the date, this is what our dataset looks like:

| Index  |  Position | Track Name | Artist | Streams | URL | Date | Region | Month | Day | 
|----------|------------|----------------------------|---------------|-------|---------------------------------------------------|------------|-------|-----|---|
| 0 | 1 | Reggaetón Lento (Bailemos) | CNCO | 19272 | https://open.spotify.com/track/3AEZUABDXNtecAO... | 2017-01-01 | ec | 1 | 1 |
| 1 | 2 | Chantaje | Shakira | 19270 | https://open.spotify.com/track/6mICuAdrwEjh6Y6... | 2017-01-01 | ec | 1 | 1 |
| 2 | 3 | Otra Vez (feat. J Balvin) | Zion & Lennox | 15761 | https://open.spotify.com/track/3QwBODjSEzelZyV... | 2017-01-01 | ec | 1 | 1 |
| 3 | 4 | Vente Pa' Ca | Ricky Martin | 14954 | https://open.spotify.com/track/7DM4BPaS7uofFul... | 2017-01-01 | ec | 1 | 1 |
| 4 | 5 | Safari | J Balvin | 14269 | https://open.spotify.com/track/6rQSrBHf7HlZjtc... | 2017-01-01 | ec | 1 | 1 |


To find the top artist for each month, we'd like to organize our dataset by months. Each row will correspond to a track for each day. Since we're looking for the top artists for the entire month, we'll need to add up the number of streams for each day to get the total for the month:

<img width="800" src="https://drive.google.com/uc?export=view&id=1xtGLT-PhIiMCop9-05H0zQuQiI5o4aYd">


This will give us the total number of streams for each artist, which we then, could find the top artist. 

We've written two functions to help you perform this step. Now, let's organize our data!

**Exercise**

<left><img width="100" src="https://drive.google.com/uc?export=view&id=1E8tR7B9YYUXsU_rddJAyq0FrM0MSelxZ"></left>


1. Call the function **organize_by_month()** on **add_day** to organize all the tracks by month. The result will be a dictionary with the month as the key and the tracks as the value. Store in **organized.**
2. Call the function **aggregate()** to sum all the values for each artist and assign to **aggregated**.

In [110]:
def organize_by_month(cleaned_music):
    months = [1,2,3,4,5,6,7,8,9,10,11,12]
    
    organized = dict()
    for month in months:
        tracks_in_month = []
        for track in cleaned_music:
            if track[-2] == month:
                tracks_in_month.append(track)
        organized[month] = tracks_in_month
    return organized

def aggregate(organized):
    months = [1,2,3,4,5,6,7,8,9,10,11,12]
    monthly_sum = dict()

    for month in months:
        tracks = organized[month]
        # Need the track name, artist and number of streams
        groups = dict()
        for t in tracks:
            track_name = t[2]
            if track_name not in groups.keys():
                groups[track_name] = int(t[3])
            else:
                groups[track_name] += int(t[3])
        monthly_sum[month] = groups
    return monthly_sum

  
# put your code here
organized = organize_by_month(add_day)
aggregated = aggregate(organized)
aggregated[1]

{'The Weeknd': 312382426,
 'The Chainsmokers': 302742062,
 'DJ Snake': 93096199,
 'Clean Bandit': 123490587,
 'Drake': 229504802,
 'Bruno Mars': 126846321,
 'Maroon 5': 105914728,
 'Rae Sremmurd': 74895837,
 'Shakira': 76211260,
 'ZAYN': 134289888,
 'James Arthur': 95215972,
 'Migos': 127281874,
 'Major Lazer': 95333193,
 'Martin Garrix': 82157642,
 'Ariana Grande': 71129218,
 'Starley': 68028476,
 'Justin Timberlake': 45082535,
 'Shawn Mendes': 113447055,
 'Steve Aoki': 62932645,
 'Calvin Harris': 77790904,
 'Hailee Steinfeld': 63161769,
 'Machine Gun Kelly': 68986391,
 'Twenty One Pilots': 87445820,
 'Sia': 72598363,
 'CNCO': 48923888,
 'DRAM': 30335011,
 'Mike Posner': 27511696,
 'J Balvin': 57882543,
 'Fifth Harmony': 23333103,
 'Alessia Cara': 88872865,
 'Ricky Martin': 26808272,
 'The Vamps': 47312986,
 'Jonas Blue': 86183292,
 'Charlie Puth': 61216008,
 'Aminé': 35343158,
 'Sage The Gemini': 43865441,
 'John Legend': 52914137,
 'Nevada': 28731221,
 'Alan Walker': 69943712,
 'Rihanna': 56017166,
 'Zion & Lennox': 28568060,
 'Zara Larsson': 73209012,
 'Alok': 44616520,
 'Robin Schulz': 45238792,
 'Big Sean': 47417679,
 'Justin Bieber': 63837696,
 'DNCE': 18002657,
 'Carlos Vives': 27017323,
 'Desiigner': 22070440,
 'NEIKED': 26257142,
 'J. Cole': 55542536,
 'Daddy Yankee': 23653786,
 'Sebastian Yatra': 27177267,
 '21 Savage': 56864440,
 'Adele': 60449753,
 'Zay Hilfigerrr': 15346701,
 'Enrique Iglesias': 15430392,
 'Coldplay': 31540250,
 'gnash': 22280727,
 'Lil Wayne': 20771702,
 'Martin Jensen': 38223290,
 'Rob $tone': 21498028,
 'MC G15': 11692125,
 'Mike Perry': 19688219,
 "Rag'n'Bone Man": 28191699,
 'Lukas Graham': 17805589,
 'Kungs': 16637990,
 'Young M.A': 10791091,
 'Cashmere Cat': 21195346,
 'Noah Cyrus': 27181360,
 'Luke Christopher': 25873178,
 'Chance The Rapper': 15556843,
 'Little Mix': 38061237,
 'Ozuna': 52724061,
 'G-Eazy': 80290094,
 'FRENSHIP': 18506892,
 'Michael Jackson': 1896952,
 'IAmChino': 19059365,
 'Maluma': 52004231,
 'Chino & Nacho': 14736653,
 'Petit Biscuit': 25988350,
 'Cheat Codes': 20442782,
 'MØ': 16142254,
 'Jon Bellion': 33502755,
 'Andy Grammer': 18272052,
 'Wisin': 25371172,
 'Queen': 1879999,
 'Young Thug': 15327554,
 'Lil Uzi Vert': 35017687,
 'Vice': 20454998,
 'Ed Sheeran': 453622763,
 'Foster The People': 1918119,
 'Childish Gambino': 26566928,
 'Galantis': 24355711,
 'Pharrell Williams': 952655,
 'Niall Horan': 27302962,
 'Flume': 15931528,
 'Bebe Rexha': 38493368,
 'David Guetta': 16234538,
 'Macklemore & Ryan Lewis': 1197814,
 'Piso 21': 29684782,
 'Hearts & Colors': 21340822,
 'The Jackson 5': 1057952,
 'AJR': 26714702,
 'Calum Scott': 16229697,
 'KYLE': 25083408,
 'Nause': 7378139,
 'Marvin Gaye': 1084382,
 'Kiiara': 4820345,
 'Future': 31559667,
 'Charly Black': 13220821,
 'Nicky Jam': 11100400,
 'Thalía': 396612,
 'Flo Rida': 15466675,
 'Dante Klein': 11329589,
 'Mark Ronson': 1601226,
 'Gente De Zona': 377647,
 'Travis Scott': 27447216,
 'San Holo': 17044936,
 'Farruko': 11149779,
 'State of Sound': 4120947,
 'Joel Adams': 7465793,
 'Anne-Marie': 3518987,
 'Marc E. Bassy': 7393811,
 'Sean Paul': 18876880,
 'Kygo': 19092332,
 'Skrillex': 343807,
 'Tove Lo': 5292923,
 'James Hersey': 5591092,
 'Eminem': 63061980,
 'M.I.A.': 341003,
 'James Bay': 13880587,
 'Kanye West': 3031051,
 'KREAM': 14299972,
 'Post Malone': 106560587,
 'MiC LOWRY': 11450506,
 'Stevie Wonder': 812603,
 'JAY Z': 325951,
 'JP Cooper': 17316386,
 'DVBBS': 16882279,
 'Lady Gaga': 10535973,
 'Milky Chance': 12620634,
 'Passenger': 10749552,
 'Sam Smith': 27450387,
 'Mura Masa': 12856715,
 'Selena Gomez': 26464438,
 'The Killers': 4031050,
 'Bryson Tiller': 687523,
 'Hozier': 2621282,
 'Isaiah': 17919765,
 'VÉRITÉ': 3488819,
 'Chris Brown': 10762938,
 'Snakehips': 22734080,
 'The xx': 19697123,
 'Tyga': 521824,
 'London Grammar': 475026,
 'Rudimental': 1146583,
 'Don Omar': 7489794,
 'Jax Jones': 14368996,
 'A R I Z O N A': 11369523,
 'Halsey': 7947481,
 'Tiësto': 1883351,
 'Luis Fonsi': 76996707,
 'Olivia Holt': 9606300,
 'Stanaj': 9086655,
 'Lauv': 17446382,
 'La La Land Cast': 5101191,
 'Ryan Gosling': 6517271,
 'Julia Michaels': 19721058,
 'PnB Rock': 4555698,
 'Gucci Mane': 12843042,
 'Oasis': 1874703,
 'John Mayer': 6489255,
 'Ugly God': 756935,
 'Imagine Dragons': 30338228,
 'Anuel Aa': 3134044,
 'PARTYNEXTDOOR': 774561,
 'James Blunt': 458310,
 'Cosculluela': 781209,
 'Beyoncé': 373292,
 'Emma Stone': 796593,
 'Justin Hurwitz': 385300,
 'Kodak Black': 15436197,
 'Camila Cabello': 59981526,
 'Dua Lipa': 34859554,
 'Lil Pump': 21469043,
 'NF': 21969317,
 'Marshmello': 19009082,
 'Natti Natasha': 14592172,
 'Khalid': 21302659,
 'Portugal. The Man': 13133556,
 'Danny Ocean': 11922583,
 'Bad Bunny': 18385416,
 'Anitta': 25107669,
 'Becky G': 11399743,
 'Cardi B': 24456421,
 'Logic': 12175965,
 'French Montana': 12551625,
 'Kendrick Lamar': 35865303,
 'Big Shaq': 10398311,
 'Offset': 12275077,
 'Alex Sensation': 8633587,
 'Axwell /\\ Ingrosso': 13771958,
 'Nacho': 8203483,
 'Demi Lovato': 18135081,
 'MC Fioti': 8125693,
 'A$AP Ferg': 9925968,
 'Rita Ora': 16409926,
 'Famous Dex': 8328935,
 'Joey Montana': 7719889,
 'Avicii': 15273088,
 'DJ Khaled': 13702503,
 'Liam Payne': 12238996,
 'Jason Derulo': 15747994,
 'XXXTENTACION': 19122017,
 'OutKast': 727522,
 'Miguel': 7811296,
 'Lil Xan': 7781589,
 'Zedd': 5868394,
 'Romeo Santos': 6612004,
 'BTS': 6982837,
 'Macklemore': 11074428,
 'Wolfine': 7204071,
 'Manuel Turizo': 6064173,
 'Taylor Swift': 21910739,
 'MC Kevinho': 2620337,
 'Bee Gees': 587405,
 'Chris Jeday': 5560996,
 'Earth, Wind & Fire': 582624,
 'Maggie Lindemann': 5478884,
 'Jesse & Joy': 5790178,
 'NAV': 5436846,
 'P!nk': 6044627,
 'Daryl Hall & John Oates': 549012,
 'MC Jhowzinho e MC Kadinho': 1038779,
 'Shaggy': 536092,
 'The Clash': 521206,
 'Yandel': 7137646,
 'Huncho Jack': 9329755,
 'Zac Efron': 7745510,
 'Keala Settle': 8105363,
 'Louis Tomlinson': 5526157,
 'Toto': 470156,
 'Yo Gotti': 457182,
 '6ix9ine': 4536155,
 'Journey': 450196,
 'AC/DC': 442882,
 'Hugh Jackman': 18940083,
 'Loren Allred': 5789583,
 'Ziv Zaifman': 5714833,
 'Harry Styles': 4142675,
 'SZA': 4375897,
 'Matt Terry': 4224261,
 'Abraham Mateo': 2911370,
 'A Boogie Wit da Hoodie': 2372777,
 'Sam Hunt': 1439090,
 'Juan Magán': 4257898,
 'Lil Skies': 2201190,
 'Michelle Williams': 1594526,
 'YBN Nahmir': 1029698,
 'Austyn Johnson': 506561}

## Finding the top artist for each group

Now, that we've grouped and aggregated our data by each month, we'll use [sorted() function](https://docs.python.org/3/library/functions.html#sorted) to sort each list by streams. To review, sorted is a function that will sort our data structure:

```python
streams = ["ed","sheeran","beyonce","kanye","west"]
sorted(streams)
```

This would print the list of strings in alphabetical order

```python
['beyonce', 'ed', 'kanye', 'sheeran', 'west']
```

Now, if we wanted to sort by the second character in each string, we can sort by inserting a **lambda** function within the **key**:

```python
streams = ["ed","sheeran","beyonce","kanye","west"]
sorted(streams, key = lambda x: x[1])
```

This would print out:

```python
['kanye', 'ed', 'beyonce', 'west', 'sheeran']
```

Link to the sorted documentation [here](https://docs.python.org/3/library/functions.html#sorted).

**Exercise**

<left><img width="100" src="https://drive.google.com/uc?export=view&id=1E8tR7B9YYUXsU_rddJAyq0FrM0MSelxZ"></left>


1. For each month in the dictionary **aggregated**, sort the tracks by total streams.
2. To sort the tracks for each month:
  - Create an empty list called **top_songs_by_month.**
  - Loop through each month by doing the following:
    - Use the **dict.items()** method on **aggregated[month]** to pull the month values out of the dictionary
    - Use the **sorted()** function to sort all the values.
        - Within **sorted()**, set the **key** parameter to a lambda function that sorts by the total streams.
        - Set the **reverse** parameter to **True** so everything is in descending order.
        - Store the sorted values in **sorted_dict.**
    - Append the 0 index of the resulting values to **top_songs_by_month**.
3. Print **top_songs_by_month**

In [117]:
# put your code here
top_songs_by_month = []
for mes, streams in aggregated.items():
    sorted_dict = sorted(streams.items(), key=lambda x: x[1], reverse=True)
    top_songs_by_month.append(sorted_dict[0])
top_songs_by_month

[('Ed Sheeran', 453622763),
 ('Ed Sheeran', 343386934),
 ('Ed Sheeran', 1092681232),
 ('Ed Sheeran', 560919833),
 ('Kendrick Lamar', 363824152),
 ('Ed Sheeran', 271883860),
 ('Ed Sheeran', 248549698),
 ('Ed Sheeran', 210369724),
 ('Ed Sheeran', 192494084),
 ('Post Malone', 389809805),
 ('Post Malone', 368366255),
 ('Post Malone', 347694440)]